"""empty message

Revision ID: ea25aeb64d02
Revises: 
Create Date: 2019-03-13 23:12:59.439082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea25aeb64d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dept',
    sa.Column('deptno', sa.Integer(), nullable=False),
    sa.Column('dname', sa.Unicode(length=14), nullable=True),
    sa.Column('loc', sa.Unicode(length=13), nullable=True),
    sa.PrimaryKeyConstraint('deptno')
    )
    op.create_table('emp',
    sa.Column('empno', sa.Integer(), nullable=False),
    sa.Column('ename', sa.Unicode(length=10), nullable=True),
    sa.Column('job', sa.Unicode(length=9), nullable=True),
    sa.Column('mgr', sa.Integer(), nullable=True),
    sa.Column('hiredate', sa.DateTime(), nullable=True),
    sa.Column('sal', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('comm', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('dept', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept'], ['dept.deptno'], ),
    sa.ForeignKeyConstraint(['mgr'], ['emp.empno'], ),
    sa.PrimaryKeyConstraint('empno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emp')
    op.drop_table('dept')
    # ### end Alembic commands ###
